modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
issueTrackerURL="https://github.com/zeutd/GTTCore/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader


[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    # This will be displayed as your mod's logo in the Mods panel.
    logoFile="icon.png" #optional
    # Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
    # credits="Thanks to Mojang for making this great game" #optional
    # Some more fluff displayed in the Mods panel. Plug your stuff here!
    authors="${mod_author}"
    description = '''
Core mod of GregTech Tiny
'''
    [[mixins]]
        config="${mod_id}.mixins.json"
    [[dependencies.${mod_id}]]
        modId = "forge"
        mandatory = true
        versionRange = "[${forge_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[${minecraft_version},)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[${gtceu_version},)"
        ordering = "AFTER"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId = "ad_astra"
        mandatory = true
        versionRange = "[${ad_astra_version},)"
        ordering = "AFTER"
        side = "BOTH"
    [[dependencies.${mod_id}]]
        modId="create"
        mandatory=true
        versionRange="[6.0.0,)"
        ordering="AFTER"
        side="BOTH"
    [[dependencies.${mod_id}]]
        modId="kubejs"
        mandatory=true
        versionRange="[2000,)"
        ordering="AFTER"
        side="BOTH"